- name: 'create Debian 12.6'
  shell: >
    {{ foreman_provisioning_hammer }} os info --title "Debian 12.6" ||
    {{ foreman_provisioning_hammer }} os create
    --name Debian --major 12 --minor 6 --release-name 'stretch' --architectures x86_64 --family 'Debian' --media 'Debian mirror' --partition-tables 'Preseed default'

- name: 'find Debian 12.6'
  shell: >
    {{ foreman_provisioning_hammer }} --output json os info --name "Debian 12.6" ||
    {{ foreman_provisioning_hammer }} --output json os info --title "Debian 12.6"
  register: foreman_provisioning_debian126_json
  ignore_errors: True

- name: 'get CentOS 12.6 info'
  set_fact:
    foreman_provisioning_debian126: "{{ foreman_provisioning_debian126_json.stdout|from_json }}"

- name: 'find preseed templates'
  shell: >
    {{ foreman_provisioning_hammer }} --output=json template list
    --search 'name ~ "Preseed default"'
  register: preseed_templates_json

- name: 'set preseed templates'
  set_fact:
    preseed_templates: "{{ preseed_templates_json.stdout|from_json }}"

- name: 'associate preseed templates to Debian 12.6'
  shell: >
    {{ foreman_provisioning_hammer }} template add-operatingsystem --id {{ item.Id }} --operatingsystem 'Debian 12.6'
  with_items: "{{ preseed_templates }}"

- name: 'set default templates for Debian 12.6'
  shell: >
    {{ foreman_provisioning_hammer }} os set-default-template --id {{ foreman_provisioning_debian126.Id }} --provisioning-template-id {{ item.Id }}
  with_items: "{{ preseed_templates }}"
