---
hammer_devel_local_plugins: |-
  gem 'hammer_cli_foreman'
    gem 'hammer_cli_katello'
    gem 'hammer_cli_foreman_admin'
    gem 'hammer_cli_foreman_ansible'
    gem 'hammer_cli_foreman_templates'
    gem 'hammer_cli_foreman_tasks'
    gem 'hammer_cli_foreman_discovery'
    gem 'hammer_cli_foreman_virt_who_configure'
    gem 'hammer_cli_foreman_openscap'
    gem 'hammer_cli_foreman_bootdisk'
    gem 'hammer_cli_foreman_remote_execution'
hammer_devel_extra_plugins:
  - hammer-cli-foreman-ansible
  - hammer-cli-foreman-templates
  - hammer-cli-foreman-tasks
  - hammer-cli-foreman-discovery
  - hammer-cli-foreman-virt-who-configure
  - hammer_cli_foreman_openscap
  - hammer_cli_foreman_bootdisk
  - hammer-cli-katello
