---
dependencies:
  - role: etc_hosts
  - role: foreman_installer_devel_scenario
  - role: foreman_installer
    katello_repositories_version: nightly
    foreman_installer_scenario: katello-devel
    foreman_installer_additional_packages:
      - foreman-installer-katello
    foreman_installer_disable_system_checks: true
    foreman_installer_options_internal_use_only:
      - "--katello-devel-scl-ruby={{ ruby_scl_version }}"
      - "--katello-devel-admin-password {{ foreman_installer_admin_password }}"
